### ISSUE TITLE
Firebase analytics

### ISSUE THREAD

**Issue by alizahid** [tomasbasham/ember-cli-analytics#6]

**Comment by tomasbasham** [comment]
Hi, If you want to implement your own service adapters you may issue `ember g integration firebase`. This will create you a blueprint which you can use to add Firebase specific code. You could use the [mixpanel](https://github.com/tomasbasham/ember-cli-analytics/blob/master/addon/integrations/mixpanel.js) implementation as an example.

**Comment by tomasbasham** [comment]
May I close this issue? Did you manage to implement your integration?

**Comment by alizahid** [comment]
Yes, you may. There's no Firebase analytics for web. Google Analytics was the solution.
