### ISSUE TITLE
Requiring Bing ID even if I don't want to use Bing

### ISSUE THREAD

**Issue by bthomas14** [tomasbasham/ember-cli-analytics#8]
I removed the Bing object from my environment file because I don't want to use Bing. But, when I try to track events, I get the following error:
`You must pass a valid `id` to the Bing adapter`

**Comment by tomasbasham** [comment]
That's interesting. Thanks for raising this. I'll take a look ASAP

**Comment by tomasbasham** [comment]
I am going to close this issue because I have not been able to replicate the issue (and I have take a long time to respond - sorry about that). If this is still giving you trouble then please reopen the issue.
